SET INCLUDE=D:\OW19\H\OS2;%INCLUDE%
SET INCLUDE=\H;%INCLUDE%
SET INCLUDE=D:\OW19\H;%INCLUDE%
SET WATCOM=D:\OW19
SET HOME=.

REM SET INCLUDE=D:\OW16\H\OS21X;%INCLUDE%
REM SET INCLUDE=\H;%INCLUDE%
REM SET INCLUDE=D:\OW16\H;%INCLUDE%
REM SET WATCOM=D:\OW16
REM SET HOME=.


SET BLD_VENDOR=LightElf
SET BLD_VERSION=0.09
wmake